# Generated by Django 2.1.7 on 2019-03-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('componentID', models.AutoField(primary_key=True, serialize=False)),
                ('componentTitle', models.CharField(max_length=100)),
                ('componentText', models.CharField(max_length=100, null=True)),
                ('componentImage', models.CharField(max_length=100, null=True)),
                ('orderNumber', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseCECU', models.PositiveIntegerField()),
                ('courseDescription', models.CharField(max_length=200)),
                ('courseStatus', models.CharField(max_length=1)),
                ('numOfModules', models.IntegerField(default=0)),
                ('totalEnrolled', models.IntegerField(default=0)),
                ('currentEnrolled', models.IntegerField(default=0)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Category')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerTakesCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeStatus', models.CharField(max_length=1)),
                ('completionDate', models.DateField(null=True)),
                ('currentModule', models.IntegerField(null=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('moduleID', models.AutoField(primary_key=True, serialize=False)),
                ('moduleTitle', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField()),
                ('numOfComponents', models.IntegerField(default=0)),
                ('numOfQuestions', models.IntegerField(null=True)),
                ('passingMark', models.IntegerField(null=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionStatement', models.CharField(max_length=200)),
                ('qOption1', models.CharField(max_length=50)),
                ('qOption2', models.CharField(max_length=50)),
                ('qOption3', models.CharField(max_length=50)),
                ('qOption4', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=1)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('token', models.CharField(default='IWiPDi', editable=False, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailID', models.EmailField(max_length=50, null=True, unique=True)),
                ('userName', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ICE.User')),
                ('biography', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('staffID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ICE.User')),
                ('totalCECU', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='moduleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Module'),
        ),
        migrations.AddField(
            model_name='learnertakescourse',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Learner'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Instructor'),
        ),
    ]
