# Generated by Django 2.1.7 on 2019-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerAccount',
            fields=[
                ('staffID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailID', models.EmailField(max_length=50)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('totalCECU', models.IntegerField()),
            ],
        ),
    ]
