# Generated by Django 2.1.7 on 2019-03-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ICE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('componentID', models.AutoField(primary_key=True, serialize=False)),
                ('componentTitle', models.CharField(max_length=100)),
                ('componentText', models.CharField(max_length=100, null=True)),
                ('componentImage', models.CharField(max_length=100, null=True)),
                ('orderNumber', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseCECU', models.IntegerField()),
                ('courseDesc', models.CharField(max_length=200)),
                ('courseStatus', models.CharField(max_length=1)),
                ('numOfModules', models.IntegerField(default=0)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Category')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAccount',
            fields=[
                ('instructorID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('biography', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeStatus', models.CharField(max_length=1)),
                ('completionDate', models.DateField(null=True)),
                ('currentModule', models.IntegerField(null=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Courses')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.LearnerAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('moduleID', models.AutoField(primary_key=True, serialize=False)),
                ('moduleTitle', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField()),
                ('numOfComponents', models.IntegerField(default=0)),
                ('numOfQuestions', models.IntegerField(null=True)),
                ('passingMark', models.IntegerField(null=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('qAnswer1', models.CharField(max_length=50)),
                ('qAnswer2', models.CharField(max_length=50)),
                ('qAnswer3', models.CharField(max_length=50)),
                ('qAnswer4', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=1)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Modules')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='instructorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.InstructorAccount'),
        ),
        migrations.AddField(
            model_name='components',
            name='moduleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICE.Modules'),
        ),
    ]
