# Generated by Django 2.2a1 on 2019-03-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='componentImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='componentText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseCECU',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learner',
            name='totalCECU',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learnertakescourse',
            name='completionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learnertakescourse',
            name='currentModule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='numOfQuestions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='passingMark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='4lohvi', editable=False, max_length=6),
        ),
    ]
