# Generated by Django 2.1.7 on 2019-03-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='moduleID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructorID',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='learnercourse',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='learnercourse',
            name='learnerID',
        ),
        migrations.RemoveField(
            model_name='module',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='moduleID',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.DeleteModel(
            name='LearnerCourse',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
